name: Build Astro

on:
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.2'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install packages
        run: pnpm install
      - name: Check Lint
        run: pnpm run lint
      - name: Check Format with Prettier
        run: pnpm run format:check
      - name: Build
        env:
          PUBLIC_STRAPI_URL: ${{ secrets.PUBLIC_STRAPI_URL }}
        run: pnpm run build
